/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hwrqorvgqiciypxgawfv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3cnFvcnZncWljaXlweGdhd2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODUyMTIsImV4cCI6MjA3MTk2MTIxMn0.Nkon-ZGJ3gLPda_ClwykzjT_OTeB-aLyF-yctYEe_m0"